services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - test-net
    command: ["redis-server", "--loglevel", "debug"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  redis_data:
    driver: local

networks:
  test-net:
    name: test-net
    driver: bridge
